### ISSUE TITLE
Add CI to Shabdiz

### ISSUE THREAD

**Issue by masih** [stacs-srg/shabdiz#2]
Add CI build to shabdiz based on a free CI service online like `circleci` or `drone.io`

**Comment by ozgurakgun** [comment]
or travis-ci?

**Comment by grahamkirby** [comment]
Or TeamCity, given that we're already using it for other projects...

**Comment by sic2** [comment]
TeamCity will not be accessible to Masih, unless he can VPN to the cs network

About travis-ci, it is easy to setup but I think there are limitation to what you can do. 

No idea about the other tools mentioned above.

**Comment by masih** [comment]
Yes it's also possible to use travis. Last time i used travis free version it was run over shared aws instances where i had to often wait for 10-15 minutes in the queue  for my build to get triggered. That's not the case with the ones i have listed above. For my other projects i use circleci. It looked the prettiest at the time 🙂

I have no preference, happy to use teamcity given access.

Thanks

**Comment by grahamkirby** [comment]
It's now being built on TeamCity. No straightforward way to give Masih access at the moment, as it's on beast which is firewalled by ITS. You can at least tell whether the build has worked with the tick or cross against the particular commit in GitHub.

**Comment by grahamkirby** [comment]
Now also building on circleci:

https://circleci.com/gh/stacs-srg/shabdiz

Is that visible to others? It's certainly quite impressively easy to set up - starting to wonder whether we should just use that and not bother maintaining TeamCity!

**Comment by ozgurakgun** [comment]
Do you mean in general, including the linkage work?

We would then have to be very careful with not leaking privacy-sensitive data in the output. Also the input files are sensitive in the first place?

**Comment by grahamkirby** [comment]
Given that TeamCity is also building from GitHub, I don't see that there's any new risk, other than simply having to trust an additional organization. We shouldn't really put anything we're worried about on GitHub in the first place.

It might be sensible to limit the external CI to building public GitHub projects. We still need to review whether any of the currently private ones should be made public.

**Comment by ozgurakgun** [comment]
OK, I don't know how CircleCI works with private repositories. I'll look around.

**Comment by masih** [comment]
The circle CI build is added to Shabdiz repo, it seems. Can this issue be closed?

**Comment by sic2** [comment]
No problem @masih . What is the link of the build? I will add that to the README as a badge.
